title: "Brady PGY4 Supper Club"
email:
description: "A collection of monthly dinner chronicles, stories, and reflections on NYC's culinary scene from the promised land (research year)."
twitter_username:
github_username: hbhambhvani
minimal_mistakes_skin: default
search: true
remote_theme: mmistakes/minimal-mistakes
url: "https://hbhambhvani.github.io"
baseurl: ""
timezone: America/New_York

include:
  - _pages

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


author:
  name   : "The Professors"
  avatar : "/assets/images/professors.jpg"
  bio    : "PGY4s by day, foodies by night. Blogging our dinner adventures and research year shenanigans."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hbhambhvani"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hbhambhvani"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
